In [1]:
import numpy as np

In [42]:
j=[4,6,2,3,8,9]

In [43]:
d=np.array(j)

In [44]:
type(j)

list

In [45]:
j

[4, 6, 2, 3, 8, 9]

In [46]:
d

array([4, 6, 2, 3, 8, 9])

In [47]:
type(d)

numpy.ndarray

In [48]:
tuple(j)

(4, 6, 2, 3, 8, 9)

In [49]:
j

[4, 6, 2, 3, 8, 9]

In [50]:
d.shape

(6,)

In [51]:
d.ndim

1

In [52]:
s=[[4,8,90,12],[56,7,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 7, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [53]:
type(s)

list

In [54]:
arr1=np.array(s)

In [55]:
arr1

array([[ 4,  8, 90, 12],
       [56,  7, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [56]:
arr1.shape

(5, 4)

In [57]:
arr1.size

20

In [58]:
arr1.ndim

2

In [69]:
h=d.reshape(3,2)
h

array([[4, 6],
       [2, 3],
       [8, 9]])

In [62]:
d.reshape(6,1)

array([[4],
       [6],
       [2],
       [3],
       [8],
       [9]])

In [63]:
h.size

6

In [64]:
h.ndim


2

In [65]:
arr1.shape

(5, 4)

In [66]:
k=[8,4,5,84,54,58,44,54,15,17,15,16,165,235,3565,236,2652,86,286,235,35,74,5,36,25,354]

In [67]:
z=np.array(k)

In [68]:
z

array([   8,    4,    5,   84,   54,   58,   44,   54,   15,   17,   15,
         16,  165,  235, 3565,  236, 2652,   86,  286,  235,   35,   74,
          5,   36,   25,  354])

In [73]:
y=z.reshape(1,26)

In [74]:
y

array([[   8,    4,    5,   84,   54,   58,   44,   54,   15,   17,   15,
          16,  165,  235, 3565,  236, 2652,   86,  286,  235,   35,   74,
           5,   36,   25,  354]])

In [76]:
z.reshape(26,1)

array([[   8],
       [   4],
       [   5],
       [  84],
       [  54],
       [  58],
       [  44],
       [  54],
       [  15],
       [  17],
       [  15],
       [  16],
       [ 165],
       [ 235],
       [3565],
       [ 236],
       [2652],
       [  86],
       [ 286],
       [ 235],
       [  35],
       [  74],
       [   5],
       [  36],
       [  25],
       [ 354]])

In [77]:
k

[8,
 4,
 5,
 84,
 54,
 58,
 44,
 54,
 15,
 17,
 15,
 16,
 165,
 235,
 3565,
 236,
 2652,
 86,
 286,
 235,
 35,
 74,
 5,
 36,
 25,
 354]

In [79]:
list(range(3,100))

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [80]:
list(range(3,100,2))

[3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [81]:
list(range(3,100,10))

[3, 13, 23, 33, 43, 53, 63, 73, 83, 93]

In [83]:
tuple(range(3,100))

(3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99)

In [84]:
tuple(range(3,100,3))

(3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99)

In [85]:
tuple(range(3,100,10))

(3, 13, 23, 33, 43, 53, 63, 73, 83, 93)

In [86]:
list(range(-30,100))

[-30,
 -29,
 -28,
 -27,
 -26,
 -25,
 -24,
 -23,
 -22,
 -21,
 -20,
 -19,
 -18,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [87]:
list(range(-1,-10))

[]

In [88]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [92]:
np.arange(-1,-10,0.5)

array([], dtype=float64)

In [94]:
list(arange(-1,-10,0.5))

NameError: name 'arange' is not defined

In [99]:
for i in range(5,500,5):
    print('data',i)

data 5
data 10
data 15
data 20
data 25
data 30
data 35
data 40
data 45
data 50
data 55
data 60
data 65
data 70
data 75
data 80
data 85
data 90
data 95
data 100
data 105
data 110
data 115
data 120
data 125
data 130
data 135
data 140
data 145
data 150
data 155
data 160
data 165
data 170
data 175
data 180
data 185
data 190
data 195
data 200
data 205
data 210
data 215
data 220
data 225
data 230
data 235
data 240
data 245
data 250
data 255
data 260
data 265
data 270
data 275
data 280
data 285
data 290
data 295
data 300
data 305
data 310
data 315
data 320
data 325
data 330
data 335
data 340
data 345
data 350
data 355
data 360
data 365
data 370
data 375
data 380
data 385
data 390
data 395
data 400
data 405
data 410
data 415
data 420
data 425
data 430
data 435
data 440
data 445
data 450
data 455
data 460
data 465
data 470
data 475
data 480
data 485
data 490
data 495


In [95]:
j=[5,45,42,65,64,25,14,254,124,6,5,54,2,5]

In [96]:
j

[5, 45, 42, 65, 64, 25, 14, 254, 124, 6, 5, 54, 2, 5]

In [102]:
even = [] 
odd = [] 
for i in range(len(j)):
    if i % 2 == 0: 
        even.append(j[i]) 
    else: 
        odd.append(j[i]) 
        

In [106]:
for i in j:
    print(i)

5
45
42
65
64
25
14
254
124
6
5
54
2
5


In [103]:
even

[5, 42, 64, 14, 124, 5, 2]

In [104]:
odd

[45, 65, 25, 254, 6, 54, 5]